FROM apache/airflow:2.9.0-python3.11

USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt .
RUN pip install --no-cache-dir \
    papermill \
    dbt-core \
    dbt-duckdb \
    duckdb \
    polars \
    httpx \
    loguru \
    nbconvert \
    ipykernel 