import polars as pl
from loguru import logger

# Helper to extract id+name from a list[struct] column
def extract_bridge_table(df, col, id_field, name_field):
    return (
        df.select(['anime_id', col])
        .explode(col)
        .select([
            pl.col('anime_id'),
            pl.col(col).struct.field(id_field).alias(id_field),
            pl.col(col).struct.field(name_field).alias(name_field),
        ])
        .drop_nulls()
    )

# This function is meant to overwrite the merge tables in the silver layer with the dataframes generated by the jupyter notebook.
def overwrite_table(con, df, merge_table: str) -> None:
    #Splitting table name and schema name from variable:
    table_name = merge_table.split('.')[-1]
    schema_name = merge_table.split('.')[0]

    # Get the columns of the existing merge table in DuckDB
    existing_cols = [
        row[0] for row in 
        con.execute(f"SELECT column_name FROM information_schema.columns WHERE table_name = '{table_name}' AND table_schema = '{schema_name}'").fetchall()
    ]
    
    df_cols = df.columns
    
    # Check for mismatches
    missing_in_df = set(existing_cols) - set(df_cols)
    extra_in_df = set(df_cols) - set(existing_cols)
    
    if missing_in_df or extra_in_df:
        raise ValueError(
            f"Column mismatch for {merge_table}!\n"
            f"  In DuckDB but not in DataFrame: {missing_in_df or 'none'}\n"
            f"  In DataFrame but not in DuckDB: {extra_in_df or 'none'}"
        )
    
    # Overwrite the merge table
    con.execute(f"DELETE FROM {merge_table}")
    con.execute(f"INSERT INTO {merge_table} SELECT * FROM df")
    
    count = con.execute(f"SELECT COUNT(*) FROM {merge_table}").fetchone()[0]
    logger.info(f"Overwrote {merge_table}: {count} rows written")


#This function upserts the merge tables (overwitten by the above function) into the final tables in the silver (curated) layer.
def upsert_table(con, source_table: str, dest_table: str, key_cols: list[str]) -> None:
    reserved_keywords = {'source', 'type', 'rank', 'year'}  # add any others if needed
    def quote_col(col):
        return f'"{col}"' if col in reserved_keywords else col

    # Get all columns from the destination table
    dest_schema = dest_table.split('.')[0]
    dest_name = dest_table.split('.')[-1]
    
    all_cols = [
        row[0] for row in
        con.execute(f"""
            SELECT column_name FROM information_schema.columns 
            WHERE table_schema = '{dest_schema}' AND table_name = '{dest_name}'
            ORDER BY ordinal_position
        """).fetchall()
    ]
    
    non_key_cols = [c for c in all_cols if c not in key_cols]
    
    join_condition = ' AND '.join(
        [f"target.{quote_col(k)} = src.{quote_col(k)}" for k in key_cols]
        )
    
    update_clause = ', '.join(
        [f"{quote_col(c)} = src.{quote_col(c)}" for c in non_key_cols]
        )
    
    insert_cols = ', '.join([quote_col(c) for c in all_cols])
    insert_vals = ', '.join([f"src.{quote_col(c)}" for c in all_cols])
    
    merge_sql = f"""
        MERGE INTO {dest_table} target
        USING {source_table} src
        ON {join_condition}
        WHEN MATCHED THEN
            UPDATE SET {update_clause}
        WHEN NOT MATCHED THEN
            INSERT VALUES ({insert_vals})
    """

    print(merge_sql)
    
    con.execute(merge_sql)
    
    count = con.execute(f"SELECT COUNT(*) FROM {dest_table}").fetchone()[0]
    logger.info(f"Upserted {source_table} → {dest_table}: {count} total rows now in table")